sudo: false
language: ruby
rvm:
  - 2.2.2
  - 2.1
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.0.gemfile
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_5.0.gemfile
before_install: gem install bundler -v 1.13.6
